// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServicePlan.Infrastructure;

namespace ServicePlan.Infrastructure.Migrations
{
    [DbContext(typeof(ServicePlanContext))]
    partial class ServicePlanContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ServicePlan.Domain.AggregateRoot.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .HasMaxLength(300);

                    b.Property<DateTime>("BeginTime");

                    b.Property<DateTime?>("BookTime");

                    b.Property<bool>("Booked");

                    b.Property<string>("Description")
                        .HasMaxLength(500);

                    b.Property<DateTime>("EndTime");

                    b.Property<string>("Location")
                        .HasMaxLength(200);

                    b.Property<Guid?>("PlanId");

                    b.Property<Guid?>("RoadShowWeekSchedulerId");

                    b.Property<string>("Sale")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("RoadShowWeekSchedulerId");

                    b.ToTable("Appointment");
                });

            modelBuilder.Entity("ServicePlan.Domain.AggregateRoot.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Creation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.Property<Guid?>("ServicePlanId");

                    b.Property<byte>("Type");

                    b.HasKey("Id");

                    b.HasIndex("ServicePlanId");

                    b.ToTable("Attachment");
                });

            modelBuilder.Entity("ServicePlan.Domain.AggregateRoot.EmailRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationTime");

                    b.Property<DateTime?>("ResponseTime");

                    b.Property<Guid?>("ServicePlanId");

                    b.Property<bool?>("Success");

                    b.HasKey("Id");

                    b.HasIndex("ServicePlanId");

                    b.ToTable("EmailRecord");
                });

            modelBuilder.Entity("ServicePlan.Domain.AggregateRoot.RoadShowWeekScheduler", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BeginTime");

                    b.Property<DateTime>("EndTime");

                    b.Property<string>("KeyIdeaAndTopic")
                        .HasMaxLength(1000);

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.ToTable("RoadShowWeekScheduler");
                });

            modelBuilder.Entity("ServicePlan.Domain.AggregateRoot.ServicePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte>("AuditState");

                    b.Property<string>("AuditUser")
                        .HasMaxLength(50);

                    b.Property<DateTime>("BeginTime");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<DateTime>("EndTime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<byte>("PlanState");

                    b.Property<byte>("PlanType");

                    b.Property<string>("ProductId")
                        .HasMaxLength(50);

                    b.Property<string>("QcUser")
                        .HasMaxLength(50);

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<byte>("ValidationState");

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.ToTable("ServicePlan");
                });

            modelBuilder.Entity("ServicePlan.Domain.AggregateRoot.ServiceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClientFocusKeyPoint")
                        .HasMaxLength(500);

                    b.Property<bool?>("Continue");

                    b.Property<string>("Feedback")
                        .HasMaxLength(1000);

                    b.Property<string>("IndustryId")
                        .HasMaxLength(50);

                    b.Property<string>("ModificationRequirement")
                        .HasMaxLength(1000);

                    b.Property<string>("NewRequirement")
                        .HasMaxLength(1000);

                    b.Property<int>("PlanTypeId");

                    b.Property<int?>("Score");

                    b.Property<Guid?>("ServicePlanId");

                    b.Property<DateTime>("ServiceTime");

                    b.Property<string>("Subject")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("ServicePlanId");

                    b.ToTable("ServiceRecord");
                });

            modelBuilder.Entity("ServicePlan.Domain.AggregateRoot.Appointment", b =>
                {
                    b.HasOne("ServicePlan.Domain.AggregateRoot.RoadShowWeekScheduler")
                        .WithMany("Appointments")
                        .HasForeignKey("RoadShowWeekSchedulerId");

                    b.OwnsMany("ServicePlan.Domain.AggregateRoot.ClientUser", "ClientUsers", b1 =>
                        {
                            b1.Property<Guid>("_id")
                                .ValueGeneratedOnAdd();

                            b1.Property<Guid>("AppointmentId");

                            b1.Property<string>("ClientId");

                            b1.Property<string>("ClientName");

                            b1.Property<string>("ClientShortName");

                            b1.Property<string>("ClientUserId");

                            b1.Property<string>("FirstName");

                            b1.Property<string>("LastName");

                            b1.HasKey("_id");

                            b1.HasIndex("AppointmentId");

                            b1.ToTable("Appointment_ClientUsers");

                            b1.HasOne("ServicePlan.Domain.AggregateRoot.Appointment")
                                .WithMany("ClientUsers")
                                .HasForeignKey("AppointmentId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("ServicePlan.Domain.AggregateRoot.Attachment", b =>
                {
                    b.HasOne("ServicePlan.Domain.AggregateRoot.ServicePlan")
                        .WithMany("Attachments")
                        .HasForeignKey("ServicePlanId");
                });

            modelBuilder.Entity("ServicePlan.Domain.AggregateRoot.EmailRecord", b =>
                {
                    b.HasOne("ServicePlan.Domain.AggregateRoot.ServicePlan")
                        .WithMany("EmailRecords")
                        .HasForeignKey("ServicePlanId");

                    b.OwnsOne("ServicePlan.Domain.AggregateRoot.ClientUser", "ClientUser", b1 =>
                        {
                            b1.Property<Guid>("EmailRecordId");

                            b1.Property<string>("ClientId");

                            b1.Property<string>("ClientName")
                                .HasMaxLength(200);

                            b1.Property<string>("ClientShortName")
                                .HasMaxLength(200);

                            b1.Property<string>("ClientUserId");

                            b1.Property<string>("FirstName")
                                .HasMaxLength(100);

                            b1.Property<string>("LastName")
                                .HasMaxLength(100);

                            b1.HasKey("EmailRecordId");

                            b1.ToTable("EmailRecord");

                            b1.HasOne("ServicePlan.Domain.AggregateRoot.EmailRecord")
                                .WithOne("ClientUser")
                                .HasForeignKey("ServicePlan.Domain.AggregateRoot.ClientUser", "EmailRecordId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("ServicePlan.Domain.AggregateRoot.ServicePlan", b =>
                {
                    b.OwnsMany("ServicePlan.Domain.AggregateRoot.AuditHistory", "AuditHistory", b1 =>
                        {
                            b1.Property<Guid>("_id")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Operation")
                                .IsRequired()
                                .HasMaxLength(100);

                            b1.Property<string>("Result")
                                .IsRequired()
                                .HasMaxLength(300);

                            b1.Property<Guid>("ServicePlanId");

                            b1.Property<string>("User")
                                .IsRequired()
                                .HasMaxLength(50);

                            b1.HasKey("_id");

                            b1.HasIndex("ServicePlanId");

                            b1.ToTable("AuditHistory");

                            b1.HasOne("ServicePlan.Domain.AggregateRoot.ServicePlan")
                                .WithMany("AuditHistory")
                                .HasForeignKey("ServicePlanId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("ServicePlan.Domain.AggregateRoot.DataReport", "DataReport", b1 =>
                        {
                            b1.Property<Guid>("ServicePlanId");

                            b1.Property<string>("Abstract")
                                .HasMaxLength(2000);

                            b1.Property<string>("ReportTitle")
                                .HasMaxLength(200);

                            b1.HasKey("ServicePlanId");

                            b1.ToTable("ServicePlan");

                            b1.HasOne("ServicePlan.Domain.AggregateRoot.ServicePlan")
                                .WithOne("DataReport")
                                .HasForeignKey("ServicePlan.Domain.AggregateRoot.DataReport", "ServicePlanId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("ServicePlan.Domain.AggregateRoot.RoadShow", "RoadShow", b1 =>
                        {
                            b1.Property<Guid>("ServicePlanId");

                            b1.Property<string>("Address")
                                .HasMaxLength(500);

                            b1.HasKey("ServicePlanId");

                            b1.ToTable("ServicePlan");

                            b1.HasOne("ServicePlan.Domain.AggregateRoot.ServicePlan")
                                .WithOne("RoadShow")
                                .HasForeignKey("ServicePlan.Domain.AggregateRoot.RoadShow", "ServicePlanId")
                                .OnDelete(DeleteBehavior.Cascade);

                            b1.OwnsMany("ServicePlan.Domain.AggregateRoot.ClientUser", "ClientUsers", b2 =>
                                {
                                    b2.Property<Guid>("_id")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("ClientId");

                                    b2.Property<string>("ClientName");

                                    b2.Property<string>("ClientShortName");

                                    b2.Property<string>("ClientUserId");

                                    b2.Property<string>("FirstName");

                                    b2.Property<string>("LastName");

                                    b2.Property<Guid>("RoadShowServicePlanId");

                                    b2.HasKey("_id");

                                    b2.HasIndex("RoadShowServicePlanId");

                                    b2.ToTable("ServicePlan_ClientUsers");

                                    b2.HasOne("ServicePlan.Domain.AggregateRoot.RoadShow")
                                        .WithMany("ClientUsers")
                                        .HasForeignKey("RoadShowServicePlanId")
                                        .OnDelete(DeleteBehavior.Cascade);
                                });
                        });
                });

            modelBuilder.Entity("ServicePlan.Domain.AggregateRoot.ServiceRecord", b =>
                {
                    b.HasOne("ServicePlan.Domain.AggregateRoot.ServicePlan")
                        .WithMany("ServiceRecords")
                        .HasForeignKey("ServicePlanId");

                    b.OwnsMany("ServicePlan.Domain.AggregateRoot.ClientUser", "ClientUsers", b1 =>
                        {
                            b1.Property<Guid>("_id")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("ClientId");

                            b1.Property<string>("ClientName")
                                .HasMaxLength(200);

                            b1.Property<string>("ClientShortName")
                                .HasMaxLength(200);

                            b1.Property<string>("ClientUserId");

                            b1.Property<string>("FirstName")
                                .HasMaxLength(100);

                            b1.Property<string>("LastName")
                                .HasMaxLength(100);

                            b1.Property<Guid>("ServiceRecordId");

                            b1.HasKey("_id");

                            b1.HasIndex("ServiceRecordId");

                            b1.ToTable("ServiceRecord_ClientUsers");

                            b1.HasOne("ServicePlan.Domain.AggregateRoot.ServiceRecord")
                                .WithMany("ClientUsers")
                                .HasForeignKey("ServiceRecordId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
